---
dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: ${PWD}/target/travis-settings/java/install.sh
script: ${PWD}/target/travis-settings/java/script.sh
after_success: ${PWD}/target/travis-settings/java/after_success.sh
env:
  global:
  - secure: Vn6+ANxKSDunCvZtuoadgOYw6Vb5h0ulPGJI9un+erE2JkD6Z3xZWUnc4kPPuIpD/SSYAHc0SLNt6+gV/PY9P7rbn72oxQJArZcK1fnEgOtRBU68YJIhg/sw5sonlXJOfrXfSMiIe+ghAGjcW6Dmd8LcG7wBrVPgMmZNG+rOODShwwjV3mLb2NIJKKZpOfiNs93Qikl/HGSsjWIacvIf2EHqSvycPfAh0VjvSKMDworFIv4GXbXewmGtypu3W8MM0S0kxYXIGLNWrtQbolkswdjn2J+QWH1n/tUpAzK0oH/aoonGtxZE1knkD18e5XMsFk1jrUxl45h/w5YGsBgfPx/MLK2i1vKPGoiv4QDDjQvlzDy3CgYP++GsbqMXEBzdW4mxFFnzoXpxojZz0qGkBX+2zVEF6CfBZxvJmfaRaJsTreUpWim08VWPcmusHmo4vm7/rUhaW7L05zEewTzoRFqmz96J7X7uHLyVzExZvLqStw0E4dpBBw4JzQql0D1ESmXCB/+uYfL8W+3nKKgoDhVg4y9+TBTwGGor9otCh5DpQQWesXGD7VHmfGLzTMoF71MpuxeP8ulMvHvVHjVSYeAu9whuGK9Tcjuiqxsp2h36xUPFOhDyxH1kyop6hod2WqkRV8gqBxUtEdiBnxOo5twC20hTHTWDZYhya4/+2r0=
  - secure: KnlcXPsCfg/TML3tZmEhl5eB1nS4SJ0+4z4ajbkXUuqIJSczCA2z/zsGQc4rscBwS5v9v5zkDmspkzDnVoOXsBjYbZPjLo5gyL7pB31ZsX5AP/aOfQg6Q+n5prpBp6i2tofMeo9VuBzVQUxBk0sQNvl5uSexZ5r0GM5UvlmnkMNJbCYV4l9WxU9+1Y3ypE4zYBTfSHniK3qFFHpPyWGRsFKGQV/EWLT6qLZno/xggqyzXdgpxc/4vHGpqqygcc17oIz4t97qthrtnIuzxIDeFpHvqZGfCrq6qiaXUTuIgqZmIC00nH1XYgwvMZ9ffsZYAi1KwwFCaBvDWGPn9Z1fZEnFerNSefjdmsmQYH1eBhdM1Qit+8aZ35bIVjz0zIwlWtAz/qcxqLZ/z95+vf9jKqj+SwtDrLTao2IGUW0wSm7ablPVh4eoorgRSfUs/xCvtW4oM5pON06JqjhFBAaqXB0C4cikSs6oOtkYWG1fG+lDMNYuPOW2Sa/Mr6f7SS3pBm0ge9nhwlzcK8zMPzI6cVXvSPJnRT3SF9FjdTlqdiNihxn8BpvGO5BdNW1yOnZ8iVANsSlWkqm/MPZTrv/J4M9DoSJcqtPUsvlTAdf/FJoXoWhK4WGQzdVtqUaekM+9TMSH+QlGYfQWO9aVpkT7E8rjC+m1TIGHli3MzayAAcw=
