dist: xenial
language: java
os: linux
jdk:
- openjdk17
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh"
script: "${PWD}/target/travis-settings/java/script.sh"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
env:
  global:
    secure: m7Z7TRYo61uKulweBI0pjrSJdorP+cRziFno2rIJfKrQlbGG+0UBGj3JlIrCmf0JdSVjzljNvAjL6MOmfanZKnwXzAkmo9pgjjSL1tsfCSZpTdUikozBf8ra950chfPYWOiaWXu+rMbcGhqmnIwQaklywCa32KIdjmtcDeJMCcGRs/1cpBNGs+pGDEktdvgM1Jx2zkeSRNBsvQh/1pEU9NLzRdWMosx8azc47nz25wAkyQQrNRmtUx5nQA/qXaiHPrZGOcB/9kB13jj06Y9wydZXve2ApUDv5e7qawEypsChSW7W5jQ4xupn8IGQa7HNr5c2+RY7ExBkToUQfZcAUQd+kiW2dlbe/DBk3XqFgh6ZFcm6uEq7TibJ5BxWnqdc/rX3v3dyhQK4n+auVBhLlndiObB2qma06s30q83SAz5k8E3yW/QxwEbn9jOrefreBaqgDp9Cawtci8v13Vv0ZoQSeGr478HSjY+9+F4+0Cy4+nTJDlY1OTld3IV+W8afvmL9ebPbsDGwhl5wsNwVN0LzNZjSaBbqpOA4QjK/X6QtDiM7qRaxQdrjgBMng2cVQy8nOTULyYT+dtkLM6aNtSGnYW9gebAJYhR19koObH6x0uYbpLFtS/K0Y75jrUdrhyxyTSnB2OuzcQeq/ed23LCNBq6IV9o1yUp1moMdhPE=
